<?xml version="1.0"?>
<package format="2">
  <name>hexapod_core</name>
  <version>0.0.0</version>
  <description>The hexapod package</description>
  <maintainer email="blah@blah.com">Matt</maintainer>
  <license>None</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
