<?xml version="1.0"?>
<package format="2">
  <name>hexapod_vis</name>
  <version>0.0.0</version>
  <description>The hexapod package</description>
  <maintainer email="blah@blah.com">Matt</maintainer>
  <license>None</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <depend>hexapod_core</depend>

<!--  <depend>rclcpp</depend>-->  <!-- Is this included implicitly? -->
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>rclcpp</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>urdf</depend>

  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>robot_state_publisher_gui</exec_depend>
  <exec_depend>roslaunch</exec_depend>
  <exec_depend>rviz</exec_depend>
  <exec_depend>xacro</exec_depend>
  
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
